name: Release Tagging

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release version
        id: get_release_version
        run: echo "version=${GITHUB_HEAD_REF#release/}" >> $GITHUB_OUTPUT

      - name: Tag and push to main
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout main
          git pull origin main
          git tag v${{ steps.get_release_version.outputs.version }}
          git push origin main --tags
