name: Release Tagging

on:
  push:
    branches:
      - "release/*"
  pull_request:
    types:
      - closed

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release version
        id: get_release_version
        run: echo "::set-output name=version::$(echo $GITHUB_REF | cut -d'/' -f 3)"

      - name: Tag and push to main
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout main
          git pull origin main
          git tag v${{ steps.get_release_version.outputs.version }}
          git push origin main --tags
